### ISSUE TITLE
CSS File Errors

### ISSUE THREAD

**Issue by ExtremeMachine12** [tanmaypardeshi/CSC-510-Project3-PopcornPicks#1]
I am getting a lot of errors on the CSS file, even though the CSS itself is working. I tried fixing it but just messed stuff up more so I reverted the changes.

**Comment by tanmaypardeshi** [comment]
I will try and look into this issue

**Comment by tanmaypardeshi** [comment]
Can you tell me what errors you are facing? I am not seeing them and maybe I am looking at the wrong places.

**Comment by tanmaypardeshi** [comment]
I think I have fixed this. Wil re open if it is still not working
