### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by abhinav110595** [tanmaypardeshi/CSC-510-Project3-PopcornPicks#17]
when created an account, it doesn't say if the account is created or not, if we try to create an account with the same email or username then it is reflecting that this username already exist.

**Comment by ExtremeMachine12** [comment]
Did you pull from Tanmay's branch when running this?

**Comment by tanmaypardeshi** [comment]
I have fixed this issue. You should not be facing the issue once you pull my branch

**Comment by abhinav110595** [comment]
yes, It is working now. Thanks
