### ISSUE TITLE
setting up the db

### ISSUE THREAD

**Issue by abhinav110595** [tanmaypardeshi/CSC-510-Project3-PopcornPicks#20]
slight hiccups sometimes when trying to run command to set up db separately.

**Comment by abhinav110595** [comment]
I think its better to put these commands in a script and then run it. We will remove any possibility to have error.

**Comment by ExtremeMachine12** [comment]
I am adding a script on my next branch to address this. Once the branch is merged I will update the wiki and I will close this issue.

**Comment by tanmaypardeshi** [comment]
Thanks guys

**Comment by abhinav110595** [comment]
closing this issue, as it is resolved.
