### ISSUE TITLE
WorkFlows

### ISSUE THREAD

**Issue by ExtremeMachine12** [tanmaypardeshi/CSC-510-Project3-PopcornPicks#6]
We need to update the workflows so our tests and pylint are ran when we do our pull requests.

**Comment by tanmaypardeshi** [comment]
Looks like the files are already there for the workflows. Is there a need to update the secrets for this to start working for us?

**Comment by ExtremeMachine12** [comment]
Yea it looks like you added the necessary secrets so I will close this issue
